name 'attachmentgenie-timezone'
version '1.1.0'

author 'Eivind Uggedal <eivind@uggedal.com>'
license 'MIT License'
project_page 'https://github.com/attachmentgenie/puppet-module-timezone'
source 'git://github.com/attachmentgenie/puppet-module-timezone.git'
summary 'Puppet timezone Module'
description 'Module for configuring timezone.'
dependency 'puppetlabs/stdlib', '>=2.2.1'
